M48
; DRILL file {KiCad (6.0.0-0)} date Sunday, May 21, 2023 at 01:36:29 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-21T13:36:29-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X5.025Y-3.825
X5.025Y-3.825
X5.025Y-4.675
X5.025Y-4.675
T0
M30
